language: csharp
sudo: required
dist: xenial

matrix:
  include:
    - dotnet: 2.2
      mono: none
      env: DOTNETCORE=1  # optional, can be used to take different code paths in your script
    - mono: latest

solution: PSV.sln

script:
 - dotnet restore
 - dotnet test
